// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251025043904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Model.AnimalsEntity", b =>
                {
                    b.Property<int>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAnimal"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EarringCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("IdBreed")
                        .HasColumnType("int");

                    b.Property<int?>("IdFather")
                        .HasColumnType("int");

                    b.Property<int?>("IdLocation")
                        .HasColumnType("int");

                    b.Property<int?>("IdMother")
                        .HasColumnType("int");

                    b.Property<int>("IdSpecies")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdAnimal");

                    b.HasIndex("IdBreed");

                    b.HasIndex("IdFather");

                    b.HasIndex("IdLocation");

                    b.HasIndex("IdMother");

                    b.HasIndex("IdSpecies");

                    b.ToTable("Animals", (string)null);
                });

            modelBuilder.Entity("Model.ActivityLogEntity", b =>
                {
                    b.Property<int>("IdAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAudit"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdAudit");

                    b.HasIndex("IdUser");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Model.BreedEntity", b =>
                {
                    b.Property<int>("IdBreed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdBreed"));

                    b.Property<int>("IdSpecies")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("IdBreed");

                    b.HasIndex("IdSpecies");

                    b.ToTable("Breeds", (string)null);
                });

            modelBuilder.Entity("Model.DietsEntity", b =>
                {
                    b.Property<int>("IdDiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDiet"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdPlan")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("IdDiet");

                    b.HasIndex("IdPlan");

                    b.ToTable("Diets", (string)null);
                });

            modelBuilder.Entity("Model.DietItemsEntity", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<decimal?>("DailyAmountKg")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Food")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("IdDiet")
                        .HasColumnType("int");

                    b.HasKey("IdItem");

                    b.HasIndex("IdDiet");

                    b.ToTable("DietItems", (string)null);
                });

            modelBuilder.Entity("Model.FeedingPlansEntity", b =>
                {
                    b.Property<int>("IdPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlan"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdSpecies")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("IdPlan");

                    b.HasIndex("IdSpecies");

                    b.ToTable("FeedingPlans", (string)null);
                });

            modelBuilder.Entity("Model.FeedingSchedulesEntity", b =>
                {
                    b.Property<int>("IdSchedule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSchedule"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdAnimal")
                        .HasColumnType("int");

                    b.Property<int?>("IdDiet")
                        .HasColumnType("int");

                    b.Property<int?>("IdSpecies")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.HasKey("IdSchedule");

                    b.HasIndex("IdAnimal");

                    b.HasIndex("IdDiet");

                    b.HasIndex("IdSpecies");

                    b.ToTable("FeedingSchedules", (string)null);
                });

            modelBuilder.Entity("Model.HealthRecordsEntity", b =>
                {
                    b.Property<int>("IdHealthRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdHealthRecord"));

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Dose")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("DoseUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("IdAnimal")
                        .HasColumnType("int");

                    b.Property<int?>("IdVaccine")
                        .HasColumnType("int");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime?>("NextBoosterDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Veterinarian")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("IdHealthRecord");

                    b.HasIndex("IdAnimal");

                    b.HasIndex("IdVaccine");

                    b.ToTable("HealthRecords", (string)null);
                });

            modelBuilder.Entity("Model.LocationsEntity", b =>
                {
                    b.Property<int>("IdLocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLocation"));

                    b.Property<decimal?>("AreaHectares")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PastureType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("IdLocation");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("Model.BreedingRecordsEntity", b =>
                {
                    b.Property<int>("IdReproductionRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReproductionRecord"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("IdAnimal")
                        .HasColumnType("int");

                    b.Property<int?>("IdPartner")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("OffspringCount")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("IdReproductionRecord");

                    b.HasIndex("IdAnimal");

                    b.HasIndex("IdPartner");

                    b.ToTable("ReproductionRecords", (string)null);
                });

            modelBuilder.Entity("Model.RolesEntity", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdRole");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Model.SalesEntity", b =>
                {
                    b.Property<int>("IdSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSale"));

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<int>("IdAnimal")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdSale");

                    b.HasIndex("IdAnimal");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("Model.PastureTypesEntity", b =>
                {
                    b.Property<int>("IdSpecies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSpecies"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("IdSpecies");

                    b.ToTable("Species", (string)null);
                });

            modelBuilder.Entity("Model.UsersEntity", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int?>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("IdUser");

                    b.HasIndex("IdRole");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Model.VaccinesEntity", b =>
                {
                    b.Property<int>("IdVaccine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVaccine"));

                    b.Property<int?>("BoosterDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("DefaultDoseMl")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("IdVaccine");

                    b.ToTable("Vaccines", (string)null);
                });

            modelBuilder.Entity("Model.AnimalEntity", b =>
                {
                    b.HasOne("Model.BreedsEntity", "Breed")
                        .WithMany("Animals")
                        .HasForeignKey("IdBreed");

                    b.HasOne("Model.AnimalsEntity", "Father")
                        .WithMany("FatherChildren")
                        .HasForeignKey("IdFather")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Model.LocationsEntity", "Location")
                        .WithMany("Animals")
                        .HasForeignKey("IdLocation");

                    b.HasOne("Model.AnimalsEntity", "Mother")
                        .WithMany("MotherChildren")
                        .HasForeignKey("IdMother")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Model.PastureTypesEntity", "Species")
                        .WithMany("Animals")
                        .HasForeignKey("IdSpecies")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("Father");

                    b.Navigation("Location");

                    b.Navigation("Mother");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Model.ActivityLogEntity", b =>
                {
                    b.HasOne("Model.UsersEntity", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("IdUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Model.BreedsEntity", b =>
                {
                    b.HasOne("Model.PastureTypesEntity", "SpeciesEntity")
                        .WithMany("Breeds")
                        .HasForeignKey("IdSpecies")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpeciesEntity");
                });

            modelBuilder.Entity("Model.DietsEntity", b =>
                {
                    b.HasOne("Model.FeedingPlansEntity", "FeedingPlan")
                        .WithMany("Diets")
                        .HasForeignKey("IdPlan");

                    b.Navigation("FeedingPlan");
                });

            modelBuilder.Entity("Model.DietItemsEntity", b =>
                {
                    b.HasOne("Model.DietsEntity", "Diet")
                        .WithMany("DietItems")
                        .HasForeignKey("IdDiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diet");
                });

            modelBuilder.Entity("Model.FeedingPlansEntity", b =>
                {
                    b.HasOne("Model.PastureTypesEntity", "Species")
                        .WithMany("FeedingPlans")
                        .HasForeignKey("IdSpecies");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Model.FeedingSchedulesEntity", b =>
                {
                    b.HasOne("Model.AnimalsEntity", "Animal")
                        .WithMany("FeedingSchedules")
                        .HasForeignKey("IdAnimal");

                    b.HasOne("Model.DietsEntity", "Diet")
                        .WithMany("FeedingSchedules")
                        .HasForeignKey("IdDiet");

                    b.HasOne("Model.PastureTypesEntity", "Species")
                        .WithMany()
                        .HasForeignKey("IdSpecies");

                    b.Navigation("Animal");

                    b.Navigation("Diet");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Model.HealthRecordsEntity", b =>
                {
                    b.HasOne("Model.AnimalsEntity", "Animal")
                        .WithMany("HealthRecords")
                        .HasForeignKey("IdAnimal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.VaccinesEntity", "Vaccine")
                        .WithMany("HealthRecords")
                        .HasForeignKey("IdVaccine");

                    b.Navigation("Animal");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("Model.BreedingRecordsEntity", b =>
                {
                    b.HasOne("Model.AnimalsEntity", "Animal")
                        .WithMany("ReproductionRecords")
                        .HasForeignKey("IdAnimal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.AnimalsEntity", "Partner")
                        .WithMany()
                        .HasForeignKey("IdPartner");

                    b.Navigation("Animal");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Model.SalesEntity", b =>
                {
                    b.HasOne("Model.AnimalsEntity", "Animal")
                        .WithMany("Sales")
                        .HasForeignKey("IdAnimal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("Model.UsersEntity", b =>
                {
                    b.HasOne("Model.RolesEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Model.AnimalsEntity", b =>
                {
                    b.Navigation("FatherChildren");

                    b.Navigation("FeedingSchedules");

                    b.Navigation("HealthRecords");

                    b.Navigation("MotherChildren");

                    b.Navigation("ReproductionRecords");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Model.BreedsEntity", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Model.DietsEntity", b =>
                {
                    b.Navigation("DietItems");

                    b.Navigation("FeedingSchedules");
                });

            modelBuilder.Entity("Model.FeedingPlansEntity", b =>
                {
                    b.Navigation("Diets");
                });

            modelBuilder.Entity("Model.LocationsEntity", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Model.RolesEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Model.PastureTypesEntity", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Breeds");

                    b.Navigation("FeedingPlans");
                });

            modelBuilder.Entity("Model.UsersEntity", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("Model.VaccinesEntity", b =>
                {
                    b.Navigation("HealthRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
